version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'

    ldflags:
      - -s -w

    binary: hianime
    main: ./cmd/hianime

archives:
  - formats:
      - zip
    name_template: 'hianime_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true